# Generated by Django 3.1.4 on 2020-12-31 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('winThreshold', models.IntegerField()),
                ('players', models.JSONField()),
                ('colors', models.JSONField()),
                ('history', models.JSONField()),
                ('creationTime', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
