# Generated by Django 3.1.4 on 2020-12-31 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticTacToe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='history',
            field=models.JSONField(default=list),
        ),
    ]
