# Generated by Django 3.1.4 on 2020-12-31 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticTacToe', '0003_auto_20201231_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='colors',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='game',
            name='players',
            field=models.JSONField(default=list),
        ),
    ]
