# Generated by Django 3.1.4 on 2021-01-01 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticTacToe', '0004_auto_20201231_1251'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='creationTime',
            new_name='creation_time',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='winThreshold',
            new_name='win_threshold',
        ),
        migrations.AddField(
            model_name='game',
            name='started',
            field=models.BooleanField(default=False),
        ),
    ]
