# Generated by Django 3.1.4 on 2021-01-01 10:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ticTacToe', '0005_auto_20210101_0654'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='order',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='game',
            name='colors',
            field=models.JSONField(),
        ),
        migrations.RemoveField(
            model_name='game',
            name='players',
        ),
        migrations.AddField(
            model_name='game',
            name='players',
            field=models.ManyToManyField(related_name='tic_tac_toe_games', to=settings.AUTH_USER_MODEL),
        ),
    ]
