# Generated by Django 3.1.4 on 2021-01-01 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticTacToe', '0006_auto_20210101_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='creation_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
