# Generated by Django 3.1.4 on 2021-01-01 11:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import ticTacToe.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ticTacToe', '0007_auto_20210101_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='owner',
            field=models.ForeignKey(default=ticTacToe.models.get_admin, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
