# Generated by Django 3.1.4 on 2021-01-01 15:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticTacToe', '0008_game_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='field',
            field=models.JSONField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='winner_index',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='height',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='game',
            name='width',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='game',
            name='win_threshold',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100)]),
        ),
    ]
