# Generated by Django 3.1.4 on 2021-01-01 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticTacToe', '0009_auto_20210101_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='field',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
