# Generated by Django 3.1.4 on 2021-01-03 04:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticTacToe', '0010_auto_20210101_1510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='winner_index',
        ),
        migrations.AddField(
            model_name='game',
            name='win_line_direction_i',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='win_line_direction_j',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='win_line_start_i',
            field=models.IntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='game',
            name='win_line_start_j',
            field=models.IntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
    ]
